### Get All (Production)
GET https://austincalza.com/api/contacts

### Create New (Production)
POST https://austincalza.com/api/contacts
Content-Type: application/json

{
    "name": "Production Test",
    "number": "555-0000"
}